import type { Metadata } from "next";
import Head from "next/head";
import { Roboto_Mono } from "next/font/google";
import "normalize.css";
import "./globals.css";

const roboto = Roboto_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Hello World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/x-icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
